#!/bin/bash
cp "/Users/xiayue/Music/wuyin/秋湖月夜-俞逊发.mp3" "/Users/xiayue/my code/yin01/public/music/qiuhu.mp3"
cp "/Users/xiayue/Music/wuyin/紫竹调-林诗影.mp3" "/Users/xiayue/my code/yin01/public/music/zizhu.mp3"
cp "/Users/xiayue/Music/wuyin/燕归来 - 王次恒.mp3" "/Users/xiayue/my code/yin01/public/music/yanguilai.mp3"
cp "/Users/xiayue/Music/wuyin/百鸟朝凤.mp3" "/Users/xiayue/my code/yin01/public/music/bainiao.mp3"
cp "/Users/xiayue/Music/wuyin/云水禅心.mp3" "/Users/xiayue/my code/yin01/public/music/yunshui.mp3"
cp "/Users/xiayue/Music/wuyin/二泉映月.mp3" "/Users/xiayue/my code/yin01/public/music/erquan.mp3"
cp "/Users/xiayue/Music/wuyin/小胡笳-吴文光.mp3" "/Users/xiayue/my code/yin01/public/music/xiaohujia.mp3"
cp "/Users/xiayue/Music/wuyin/平湖秋月.mp3" "/Users/xiayue/my code/yin01/public/music/pinghu.mp3"
cp "/Users/xiayue/Music/wuyin/阳春白雪 -云书亦.mp3" "/Users/xiayue/my code/yin01/public/music/yangchun.mp3"
cp "/Users/xiayue/Music/wuyin/阳关三叠.mp3" "/Users/xiayue/my code/yin01/public/music/yangguan.mp3"
cp "/Users/xiayue/Music/wuyin/十面埋伏.mp3" "/Users/xiayue/my code/yin01/public/music/shimian.mp3"
cp "/Users/xiayue/Music/wuyin/胡笳十八拍.mp3" "/Users/xiayue/my code/yin01/public/music/hujia.mp3"
cp "/Users/xiayue/Music/wuyin/梅花三弄.mp3" "/Users/xiayue/my code/yin01/public/music/meihua.mp3"
cp "/Users/xiayue/Music/wuyin/广临散.mp3" "/Users/xiayue/my code/yin01/public/music/guangling.mp3"
cp "/Users/xiayue/Music/wuyin/汉宫秋月.mp3" "/Users/xiayue/my code/yin01/public/music/hangong.mp3"
echo "Done"
